# Generated by Django 3.1.4 on 2021-01-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_total_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='total_ratings',
            new_name='total_buyer_ratings',
        ),
        migrations.AddField(
            model_name='profile',
            name='total_seller_ratings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
