# Generated by Django 3.1.4 on 2020-12-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=50)),
                ('cover', models.ImageField(upload_to='profile_pics')),
                ('no_of_pages', models.IntegerField()),
                ('price', models.IntegerField()),
                ('published_date', models.DateTimeField()),
                ('authors', models.TextField(default='', max_length=70)),
                ('publications', models.TextField(default='', max_length=50)),
                ('synopsis', models.TextField(default='', max_length=200)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
