# Generated by Django 3.1.4 on 2020-12-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201216_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='publications',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
